In [1]:
import pandas as pd
import numpy as np

# 可視化用のライブラリ
from matplotlib import pyplot as plt
import seaborn as sns
%matplotlib inline

import neologdn
import MeCab

import re

In [2]:
df = pd.read_csv('all_text_wakatigaki.csv',encoding='utf-8')
df.head()

,surface,yomi,original,type,katsuyoukei,katsuyougata,内容
0,neologd,ネオログディー,NEologd,名詞-固有名詞-一般,NaN,NaN,neologd_tagger.parse(text)で各単語の原形、品詞などが1行で連続して...
1,_,_,_,記号-一般,NaN,NaN,neologd_tagger.parse(text)で各単語の原形、品詞などが1行で連続して...
2,tagger,タガー,tagger,名詞-固有名詞-一般,NaN,NaN,neologd_tagger.parse(text)で各単語の原形、品詞などが1行で連続して...
3,.,.,.,記号-一般,NaN,NaN,neologd_tagger.parse(text)で各単語の原形、品詞などが1行で連続して...
4,parse,パース,Parse,名詞-固有名詞-一般,NaN,NaN,neologd_tagger.parse(text)で各単語の原形、品詞などが1行で連続して...

## 文章毎に含まれる単語数をカウント

In [3]:
# [内容]カラムをグループ化しカウント　
# reset_index関数を使い[内容]カラムをindex部分からデータ列部分に戻す
per_sentence_word_cnt = df.groupby('内容')['original'].count().reset_index()

# カラム名を[original]から[word_cnt]に変更
per_sentence_word_cnt = per_sentence_word_cnt.rename(columns={'original':'word_cnt'})
# 確認
per_sentence_word_cnt

                                                  内容  word_cnt
0  neologd_tagger.parse(text)で各単語の原形、品詞などが1行で連続して...        26
1  まずはparse()で分かち書きした単語群は1つの文字列型になっているので「\n」で区切り、...        30
2     原形、品詞などの間には「\t」が、分かち書きされた単語と単語の区切りには「\n」が表示される        33
3  次に邪魔な文字「\t」を省きたい。よって、split('\t')を使用したいがwakatid...        41

In [4]:
# 文章全体の単語数をカウント(重複あり)
print('文章全体の単語数(重複あり)は{}語です。'.format(len(df)))

文章全体の単語数(重複あり)は130語です。

## 文章全体の単語数(重複なし)をカウント

In [5]:
unique_word_cnt = df['original'].nunique()
print('文章全体の単語数(重複なし)は{}語です。'.format(unique_word_cnt))

文章全体の単語数(重複なし)は66語です。

## 単語毎の出現回数をカウント

In [6]:
word_cnt_df = df['original'].value_counts().reset_index()

# カラム名を適切な名前に変更
word_cnt_df = word_cnt_df.rename(columns={'index':'original', 'original':'count'})

# 確認
word_cnt_df

   original  count
0        する      7
1         で      5
2         は      5
3         の      5
4         、      5
5         が      4
6         」      4
7         型      4
8         に      4
9        単語      4
10        「      3
11        t      3
12        を      3
13       れる      3
14        \      3
15        _      2
16        て      2
17       表示      2
18      リスト      2
19       品詞      2
20       原形      2
21       など      2
22    分かち書き      2
23        た      2
24        n      2
25    split      2
26       使用      2
27     text      2
28    Parse      2
29      文字列      2
..      ...    ...
36       連続      1
37       ので      1
38       次に      1
39        だ      1
40       ')      1
41        行      1
42        .      1
43        )      1
44        群      1
45        各      1
46       邪魔      1
47       文字      1
48      できる      1
49        (      1
50      区切り      1
51       「\      1
52  NEologd      1
53       関数      1
54        。      1
55  wakatid      1
56       ため      1
57       なる      1
58        間      1
59       省く      1
60       1つ      1
61      区切る      1
62       ()      1
63       いる      1
64        と      1
65   tagger      1

[66 rows x 2 columns]